#https://github.com/AntonyLeons/Ward/blob/main/docker-compose.yml
version: '3.3'
services:
    run:
        restart: unless-stopped
        container_name: ward
        ports:
            - '4000:4000'
        environment:
            - WARD_PORT=4000
            - WARD_THEME=dark
            - WARD_NAME=server-name
            - WARD_FOG=true
            #- WARD_BACKGROUND= #HexColor for background when fog is disabled
        privileged: true
        image: antonyleons/ward
