version: '3'

services:


  whoami:
    image: emilevauge/whoami
    command:
       # It tells whoami to start listening on 2001 instead of 80

       - --name=iamfoo

  monitoring:
    image: nicolargo/glances:latest-alpine
    restart: always
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"
